[[redirects]]
from = "/*"
to = "https://www.google.com/:splat"
status = 200
[[headers]]
for = "/*"
[headers.values]
Referer = "https://www.google.com/"
Cookie = "3PSIDCC=AKEyXzWsGCs0DKNURVrbdS0CTB7fYRaTWY2yvpOeMEUpYYP2JRP_egF6ccBqcnEg0KWWxiVkI4s; expires=Wed, 03-Sep-2026 03:58:43 GMT; path=/; domain=.google.com; Secure; HttpOnly; priority=high; SameSite=none"
